;;; psc-ide-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from psc-ide.el

(autoload 'psc-ide-mode "psc-ide" "\
psc-ide-mode definition

This is a minor mode.  If called interactively, toggle the
`Psc-Ide mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `psc-ide-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'psc-ide-xref-backend "psc-ide" "\
Xref backend for psc-ide.")
(register-definition-prefixes "psc-ide" '("company-psc-ide-backend" "psc-ide-"))


;;; Generated autoloads from psc-ide-backported.el

(register-definition-prefixes "psc-ide-backported" '("psc-ide-ident-"))


;;; Generated autoloads from psc-ide-flycheck.el

(autoload 'psc-ide-flycheck-insert-suggestion "psc-ide-flycheck" "\
Replace error with suggestion from psc compiler." t)
(autoload 'psc-ide-flycheck-setup "psc-ide-flycheck" "\
Setup Flycheck purescript." t)
(register-definition-prefixes "psc-ide-flycheck" '("psc-ide-flycheck-"))


;;; Generated autoloads from psc-ide-protocol.el

(register-definition-prefixes "psc-ide-protocol" '("psc-ide-"))

;;; End of scraped data

(provide 'psc-ide-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; psc-ide-autoloads.el ends here
