;;; ac-php-core-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ac-php-core.el

(let ((loads (get 'ac-php 'custom-loads))) (if (member '"ac-php-core" loads) nil (put 'ac-php 'custom-loads (cons '"ac-php-core" loads)) (put 'auto-complete 'custom-loads (cons 'ac-php (get 'auto-complete 'custom-loads)))))
(autoload 'ac-php-core-eldoc-setup "ac-php-core" "\
Enable the ElDoc support for the PHP language.
Configure the variable `eldoc-documentation-function' and
call the command `eldoc-mode'." t)
(register-definition-prefixes "ac-php-core" '("ac-php-" "case-fold"))

;;; End of scraped data

(provide 'ac-php-core-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ac-php-core-autoloads.el ends here
