;;; scratch-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from scratch.el

(defvar scratch-buffer nil "\
Non-nil if the current buffer is a scratch buffer.")
(autoload 'scratch "scratch" "\
Get a scratch buffer for the MODE.

When called interactively with a prefix arg, prompt for the mode.

(fn MODE)" t)
(register-definition-prefixes "scratch" '("scratch-"))

;;; End of scraped data

(provide 'scratch-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; scratch-autoloads.el ends here
