;;; company-terraform-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-terraform.el

(autoload 'company-terraform "company-terraform" "\
Main entry point for a company backend.
Read `company-mode` function docs for the semantics of this function.

(fn COMMAND &optional ARG &rest IGNORED)")
(autoload 'company-terraform-init "company-terraform" "\
Add terraform to the company backends." t)
(register-definition-prefixes "company-terraform" '("company-terraform-"))


;;; Generated autoloads from company-terraform-data.el

(register-definition-prefixes "company-terraform-data" '("company-terraform-"))

;;; End of scraped data

(provide 'company-terraform-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-terraform-autoloads.el ends here
