;;; copilot-chat-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from copilot-chat.el

(autoload 'copilot-chat-ask-and-insert "copilot-chat" "\
Send to Copilot a custom prompt and insert answer in current buffer at point." t)
(autoload 'copilot-chat-explain "copilot-chat" "\
Ask Copilot to explain the current selected code." t)
(autoload 'copilot-chat-review "copilot-chat" "\
Ask Copilot to review the current selected code." t)
(autoload 'copilot-chat-doc "copilot-chat" "\
Ask Copilot to write documentation for the current selected code." t)
(autoload 'copilot-chat-fix "copilot-chat" "\
Ask Copilot to fix the current selected code." t)
(autoload 'copilot-chat-optimize "copilot-chat" "\
Ask Copilot to optimize the current selected code." t)
(autoload 'copilot-chat-test "copilot-chat" "\
Ask Copilot to generate tests for the current selected code." t)
(autoload 'copilot-chat-explain-symbol-at-line "copilot-chat" "\
Ask Copilot to explain symbol under point, given the code line as background info." t)
(autoload 'copilot-chat-explain-defun "copilot-chat" "\
Mark current function definition and ask Copilot to explain it, then unmark." t)
(autoload 'copilot-chat-custom-prompt-function "copilot-chat" "\
Mark current function and ask copilot-chat with custom prompt." t)
(autoload 'copilot-chat-review-whole-buffer "copilot-chat" "\
Mark whole buffer, ask Copilot to review it, then unmark.
It can be used to review the magit diff for my change, or other people's" t)
(autoload 'copilot-chat-switch-to-buffer "copilot-chat" "\
Switch to Copilot Chat buffer, side by side with the current code editing buffer." t)
(autoload 'copilot-chat-custom-prompt-selection "copilot-chat" "\
Send to Copilot a custom prompt followed by the current selected code." t)
(autoload 'copilot-chat-custom-prompt-mini-buffer "copilot-chat" "\
Read a string with Helm completion, showing historical inputs." t)
(autoload 'copilot-chat-list "copilot-chat" "\
Open Copilot Chat list buffer." t)
(autoload 'copilot-chat-display "copilot-chat" "\
Display copilot chat buffers." t)
(autoload 'copilot-chat-insert-commit-message "copilot-chat" "\
Insert in the current buffer a copilot generated commit message." t)
(autoload 'copilot-chat-set-model "copilot-chat" "\
Set the Copilot Chat model to MODEL.

(fn MODEL)" t)
(register-definition-prefixes "copilot-chat" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-common.el

(register-definition-prefixes "copilot-chat-common" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-copilot.el

(register-definition-prefixes "copilot-chat-copilot" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-curl.el

(register-definition-prefixes "copilot-chat-curl" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-markdown.el

(register-definition-prefixes "copilot-chat-markdown" '("copilot-chat--markdown-format-data"))


;;; Generated autoloads from copilot-chat-org.el

(register-definition-prefixes "copilot-chat-org" '("copilot-chat--"))


;;; Generated autoloads from copilot-chat-request.el

(register-definition-prefixes "copilot-chat-request" '("copilot-chat--request-ask"))


;;; Generated autoloads from copilot-chat-shell-maker.el

(register-definition-prefixes "copilot-chat-shell-maker" '("copilot-chat-"))


;;; Generated autoloads from test_copilot-chat.el

(register-definition-prefixes "test_copilot-chat" '("copilot-chat-prompt-suffix" "test-major-mode"))

;;; End of scraped data

(provide 'copilot-chat-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; copilot-chat-autoloads.el ends here
