;;; css-eldoc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from css-eldoc.el

(autoload 'css-eldoc-function "css-eldoc")
(autoload 'css-eldoc-enable "css-eldoc" "\
Turn on css-eldoc in buffers where `css-mode' is active." t)
(autoload 'css-eldoc-disable "css-eldoc" "\
Disable css-eldoc." t)
(register-definition-prefixes "css-eldoc" '("turn-on-css-eldoc"))

;;; End of scraped data

(provide 'css-eldoc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; css-eldoc-autoloads.el ends here
