;;; company-php-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-php.el

(autoload 'company-ac-php-backend "company-php" "\
D COMMAND ARG IGNORED.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-php" '("company-"))

;;; End of scraped data

(provide 'company-php-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-php-autoloads.el ends here
