;;; flycheck-relint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-relint.el

(autoload 'flycheck-relint-setup "flycheck-relint" "\
Setup flycheck-package.
Add `emacs-lisp-relint' to `flycheck-checkers' and set up the checker chain." t)
(register-definition-prefixes "flycheck-relint" '("flycheck-relint--"))

;;; End of scraped data

(provide 'flycheck-relint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-relint-autoloads.el ends here
