;;; claude-shell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from claude-shell.el

(autoload 'claude-shell "claude-shell" "\
Start a Claude shell." t)
(register-definition-prefixes "claude-shell" '("claude-shell-"))


;;; Generated autoloads from claude-shell-fontifier.el

(register-definition-prefixes "claude-shell-fontifier" '("claude-shell-fontifier-"))

;;; End of scraped data

(provide 'claude-shell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; claude-shell-autoloads.el ends here
