;;; dhall-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dhall-mode.el

(autoload 'dhall-mode "dhall-mode" "\
Major mode for editing Dhall files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.dhall\\'" . dhall-mode))
(register-definition-prefixes "dhall-mode" '("dhall-"))

;;; End of scraped data

(provide 'dhall-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dhall-mode-autoloads.el ends here
