;;; textile-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from textile-mode.el

(autoload 'textile-mode "textile-mode" "\
A major mode for editing textile files.

(fn)" t)
(register-definition-prefixes "textile-mode" '("textile-"))

;;; End of scraped data

(provide 'textile-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; textile-mode-autoloads.el ends here
