;;; list-unicode-display-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from list-unicode-display.el

(autoload 'list-unicode-display "list-unicode-display" "\
Display a list of unicode characters with names matching REGEXP.
If no regexp is supplied, all characters are shown.  This takes
some time.

(fn &optional REGEXP)" t)
(autoload 'list-unicode-display-find-copy "list-unicode-display" "\
Copy a prompted character to the kill ring.

Also see `insert-char', which is similar to this command, but inserts the
character instead." t)
(register-definition-prefixes "list-unicode-display" '("list-unicode-display-"))

;;; End of scraped data

(provide 'list-unicode-display-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; list-unicode-display-autoloads.el ends here
